### ISSUE TITLE
Loading all background images despite css media query changes

### ISSUE THREAD

**Issue by rcwd** [erikyo/f2ll#5]
Hello, i tried your js class and it is working well.
I have found an issue with background images added via js, i have this scenario:

`<div id="mybgimage">.....</div>`

```
<style>
#mybgimage{
    background-image: url(myimage.jpg);
}

@media only screen and (min-width: 592px){
    background-image: url(myimage-2.jpg);
}

@media only screen and (min-width: 1280px){
    background-image: url(myimage-3.jpg);
}

@media only screen and (min-width: 1536px){
    background-image: url(myimage-4.jpg);
}
<style>
```
What happens? By checking the Chrome console, all 4 bg images are downloaded in network tab.
Is there a way to fix this?

Thanks

**Comment by erikyo** [comment]
Ciao @rcwd, thanks for the feedback!

Forgive me for asking, but didn't you perhaps intend to do that? Otherwise, the background image won't change. If it's just a typo, I'll try to create a minimal reproducible example on StackBlitz as soon as possible because this issue hasn't occurred to me before.

```css
 #mybgimage{
	 background-image: url(myimage.jpg);
 }

@media only screen and (min-width: 592px){
	#mybgimage{ background-image: url(myimage-2.jpg); }
}

@media only screen and (min-width: 1280px){
	#mybgimage{ background-image: url(myimage-3.jpg); }
}

@media only screen and (min-width: 1536px){
	#mybgimage{ background-image: url(myimage-4.jpg); }
}
```
